# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0002_auto_20160512_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=32)),
                ('short_desc', models.CharField(max_length=512)),
                ('min_price', models.IntegerField()),
                ('website', models.CharField(max_length=256)),
                ('max_dist', models.IntegerField()),
                ('max_dist_inc', models.IntegerField()),
                ('long_desc', models.TextField()),
                ('youtube_id', models.CharField(max_length=64)),
                ('youtube_title', models.CharField(max_length=128)),
                ('subcategory', models.CharField(max_length=256)),
                ('reg_date', models.DateTimeField(verbose_name='Date registered')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='band',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modapp.Category'),
        ),
    ]
