# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0003_auto_20160521_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='repertoire',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='website',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
