# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0004_auto_20160521_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Band',
            new_name='Artist',
        ),
    ]
