# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0006_artist_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=36)),
                ('value', models.FloatField()),
            ],
        ),
    ]
