# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0007_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
