# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0009_artist_total_stars'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('ip', 'value')]),
        ),
    ]
