# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0010_auto_20160702_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([]),
        ),
    ]
