# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0014_artist_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('artist_id', models.IntegerField()),
            ],
        ),
    ]
