# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 14:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submit_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 12, 14, 52, 23, 519683, tzinfo=utc), verbose_name='Date submitted'),
            preserve_default=False,
        ),
    ]
