# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0016_review_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='subject',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
