# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modapp', '0017_review_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='body',
        ),
    ]
